version: '3'

services:
  postgres: 
    image: 'postgres:9.6.1'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'joao'
      POSTGRES_PASSWORD: '123123'
      POSTGRES_DB: 'finantial'